//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBShopWeb.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructAuth", Namespace="http://schemas.datacontract.org/2004/07/OrangeBear.Security")]
    [System.SerializableAttribute()]
    public partial struct StructAuth : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OBShopWeb.AuthService.Authority> AuthoritysField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OBShopWeb.AuthService.Authority> Authoritys {
            get {
                return this.AuthoritysField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthoritysField, value) != true)) {
                    this.AuthoritysField = value;
                    this.RaisePropertyChanged("Authoritys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authority", Namespace="http://schemas.datacontract.org/2004/07/OrangeBear.Security")]
    [System.SerializableAttribute()]
    public partial class Authority : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Index {
            get {
                return this.IndexField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexField, value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthMapping", Namespace="http://schemas.datacontract.org/2004/07/OrangeBear.Security")]
    [System.SerializableAttribute()]
    public partial class AuthMapping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OBShopWeb.AuthService.Authority> AuthoritysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OBShopWeb.AuthService.Authority> Authoritys {
            get {
                return this.AuthoritysField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthoritysField, value) != true)) {
                    this.AuthoritysField = value;
                    this.RaisePropertyChanged("Authoritys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetAuth", ReplyAction="http://tempuri.org/IAuth/GetAuthResponse")]
        OBShopWeb.AuthService.StructAuth GetAuth(string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetAuthFunctions", ReplyAction="http://tempuri.org/IAuth/GetAuthFunctionsResponse")]
        System.Collections.Generic.List<OBShopWeb.AuthService.Authority> GetAuthFunctions(int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/WriteAuthFunctions", ReplyAction="http://tempuri.org/IAuth/WriteAuthFunctionsResponse")]
        void WriteAuthFunctions(System.Collections.Generic.List<OBShopWeb.AuthService.Authority> auths, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetAuthMappings", ReplyAction="http://tempuri.org/IAuth/GetAuthMappingsResponse")]
        System.Collections.Generic.List<OBShopWeb.AuthService.AuthMapping> GetAuthMappings(int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/WriteAuthMappings", ReplyAction="http://tempuri.org/IAuth/WriteAuthMappingsResponse")]
        void WriteAuthMappings(System.Collections.Generic.List<OBShopWeb.AuthService.AuthMapping> mappings, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Test", ReplyAction="http://tempuri.org/IAuth/TestResponse")]
        void Test(string title, int type, bool active, string memo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthChannel : OBShopWeb.AuthService.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<OBShopWeb.AuthService.IAuth>, OBShopWeb.AuthService.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OBShopWeb.AuthService.StructAuth GetAuth(string account) {
            return base.Channel.GetAuth(account);
        }
        
        public System.Collections.Generic.List<OBShopWeb.AuthService.Authority> GetAuthFunctions(int type) {
            return base.Channel.GetAuthFunctions(type);
        }
        
        public void WriteAuthFunctions(System.Collections.Generic.List<OBShopWeb.AuthService.Authority> auths, int type) {
            base.Channel.WriteAuthFunctions(auths, type);
        }
        
        public System.Collections.Generic.List<OBShopWeb.AuthService.AuthMapping> GetAuthMappings(int type) {
            return base.Channel.GetAuthMappings(type);
        }
        
        public void WriteAuthMappings(System.Collections.Generic.List<OBShopWeb.AuthService.AuthMapping> mappings, int type) {
            base.Channel.WriteAuthMappings(mappings, type);
        }
        
        public void Test(string title, int type, bool active, string memo) {
            base.Channel.Test(title, type, active, memo);
        }
    }
}
